Disable clang for now, it doesn't support openmp out of the box
In file included from solve.c:18:
/usr/include/dds.h:26:14: fatal error: 'omp.h' file not found